In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Loan_default.csv")

In [3]:
df = df.drop(columns=["LoanID"])

In [4]:
df.head(4)

Age  Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  \
0   56   85994       50587          520              80               4   
1   69   50432      124440          458              15               1   
2   46   84208      129188          451              26               3   
3   32   31713       44799          743               0               3   

   InterestRate  LoanTerm  DTIRatio    Education EmploymentType MaritalStatus  \
0         15.23        36      0.44   Bachelor's      Full-time      Divorced   
1          4.81        60      0.68     Master's      Full-time       Married   
2         21.17        24      0.31     Master's     Unemployed      Divorced   
3          7.07        24      0.23  High School      Full-time       Married   

  HasMortgage HasDependents LoanPurpose HasCoSigner  Default  
0         Yes           Yes       Other         Yes        0  
1          No            No       Other         Yes        0  
2         Yes           Yes        Auto          No        1  
3          No            No    Business          No        0

In [5]:
df["Loan_to_Income"] = df["LoanAmount"] / df["Income"]

In [6]:
df

Age  Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  \
0        56   85994       50587          520              80               4   
1        69   50432      124440          458              15               1   
2        46   84208      129188          451              26               3   
3        32   31713       44799          743               0               3   
4        60   20437        9139          633               8               4   
...     ...     ...         ...          ...             ...             ...   
255342   19   37979      210682          541             109               4   
255343   32   51953      189899          511              14               2   
255344   56   84820      208294          597              70               3   
255345   42   85109       60575          809              40               1   
255346   62   22418       18481          636             113               2   

        InterestRate  LoanTerm  DTIRatio    Education EmploymentType  \
0              15.23        36      0.44   Bachelor's      Full-time   
1               4.81        60      0.68     Master's      Full-time   
2              21.17        24      0.31     Master's     Unemployed   
3               7.07        24      0.23  High School      Full-time   
4               6.51        48      0.73   Bachelor's     Unemployed   
...              ...       ...       ...          ...            ...   
255342         14.11        12      0.85   Bachelor's      Full-time   
255343         11.55        24      0.21  High School      Part-time   
255344          5.29        60      0.50  High School  Self-employed   
255345         20.90        48      0.44  High School      Part-time   
255346          6.73        12      0.48   Bachelor's     Unemployed   

       MaritalStatus HasMortgage HasDependents LoanPurpose HasCoSigner  \
0           Divorced         Yes           Yes       Other         Yes   
1            Married          No            No       Other         Yes   
2           Divorced         Yes           Yes        Auto          No   
3            Married          No            No    Business          No   
4           Divorced          No           Yes        Auto          No   
...              ...         ...           ...         ...         ...   
255342       Married          No            No       Other          No   
255343      Divorced          No            No        Home          No   
255344       Married         Yes           Yes        Auto         Yes   
255345        Single         Yes           Yes       Other          No   
255346      Divorced         Yes            No   Education         Yes   

        Default  Loan_to_Income  
0             0        0.588262  
1             0        2.467481  
2             1        1.534154  
3             0        1.412638  
4             0        0.447179  
...         ...             ...  
255342        0        5.547329  
255343        1        3.655208  
255344        0        2.455718  
255345        0        0.711734  
255346        0        0.824382  

[255347 rows x 18 columns]

In [7]:
df["Estimated_EMI"] = (df["LoanAmount"] * df["InterestRate"]) / (12 * 100)

In [8]:
df

Age  Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  \
0        56   85994       50587          520              80               4   
1        69   50432      124440          458              15               1   
2        46   84208      129188          451              26               3   
3        32   31713       44799          743               0               3   
4        60   20437        9139          633               8               4   
...     ...     ...         ...          ...             ...             ...   
255342   19   37979      210682          541             109               4   
255343   32   51953      189899          511              14               2   
255344   56   84820      208294          597              70               3   
255345   42   85109       60575          809              40               1   
255346   62   22418       18481          636             113               2   

        InterestRate  LoanTerm  DTIRatio    Education EmploymentType  \
0              15.23        36      0.44   Bachelor's      Full-time   
1               4.81        60      0.68     Master's      Full-time   
2              21.17        24      0.31     Master's     Unemployed   
3               7.07        24      0.23  High School      Full-time   
4               6.51        48      0.73   Bachelor's     Unemployed   
...              ...       ...       ...          ...            ...   
255342         14.11        12      0.85   Bachelor's      Full-time   
255343         11.55        24      0.21  High School      Part-time   
255344          5.29        60      0.50  High School  Self-employed   
255345         20.90        48      0.44  High School      Part-time   
255346          6.73        12      0.48   Bachelor's     Unemployed   

       MaritalStatus HasMortgage HasDependents LoanPurpose HasCoSigner  \
0           Divorced         Yes           Yes       Other         Yes   
1            Married          No            No       Other         Yes   
2           Divorced         Yes           Yes        Auto          No   
3            Married          No            No    Business          No   
4           Divorced          No           Yes        Auto          No   
...              ...         ...           ...         ...         ...   
255342       Married          No            No       Other          No   
255343      Divorced          No            No        Home          No   
255344       Married         Yes           Yes        Auto         Yes   
255345        Single         Yes           Yes       Other          No   
255346      Divorced         Yes            No   Education         Yes   

        Default  Loan_to_Income  Estimated_EMI  
0             0        0.588262     642.033342  
1             0        2.467481     498.797000  
2             1        1.534154    2279.091633  
3             0        1.412638     263.940775  
4             0        0.447179      49.579075  
...         ...             ...            ...  
255342        0        5.547329    2477.269183  
255343        1        3.655208    1827.777875  
255344        0        2.455718     918.229383  
255345        0        0.711734    1055.014583  
255346        0        0.824382     103.647608  

[255347 rows x 19 columns]

In [9]:
df["EMI_to_Income"] = df["Estimated_EMI"] / df["Income"]

In [10]:
df["High_DTI_Flag"] = (df["DTIRatio"] > 0.4).astype(int)

In [11]:
df["Low_Credit_Flag"] = (df["CreditScore"] < 600).astype(int)

In [12]:
df["Low_Employment_Stability"] = (df["MonthsEmployed"] < 12).astype(int)

In [13]:
df["CreditLines_per_Age"] = df["NumCreditLines"] / df["Age"]

In [14]:
df["Thin_Credit_File"] = (df["NumCreditLines"] <= 1).astype(int)

In [15]:
df["Stable_Employment"] = df["EmploymentType"].isin(
    ["Government", "Salaried"]
).astype(int)

In [16]:
df["Risk_Buffer"] = (
    (df["HasCoSigner"] == "Yes") |
    (df["MaritalStatus"] == "Married")
).astype(int)

In [17]:
df['Education'].value_counts()

Education
Bachelor's     64366
High School    63903
Master's       63541
PhD            63537
Name: count, dtype: int64

In [18]:
education_map = {
    "High School": 0,
    "Bachelor's": 1,
    "Master's": 2,
    "PhD": 3
}

df["Education_Level"] = df["Education"].map(education_map)

In [19]:
df.groupby("Default")[[
    'Loan_to_Income',
    'EMI_to_Income',
    'High_DTI_Flag',
    'Low_Credit_Flag'
]].mean()

Loan_to_Income  EMI_to_Income  High_DTI_Flag  Low_Credit_Flag
Default                                                               
0              2.036172       0.022143       0.615555         0.541025
1              3.253000       0.042234       0.642465         0.586012

In [20]:
df.dtypes

Age                           int64
Income                        int64
LoanAmount                    int64
CreditScore                   int64
MonthsEmployed                int64
NumCreditLines                int64
InterestRate                float64
LoanTerm                      int64
DTIRatio                    float64
Education                    object
EmploymentType               object
MaritalStatus                object
HasMortgage                  object
HasDependents                object
LoanPurpose                  object
HasCoSigner                  object
Default                       int64
Loan_to_Income              float64
Estimated_EMI               float64
EMI_to_Income               float64
High_DTI_Flag                 int64
Low_Credit_Flag               int64
Low_Employment_Stability      int64
CreditLines_per_Age         float64
Thin_Credit_File              int64
Stable_Employment             int64
Risk_Buffer                   int64
Education_Level             

In [21]:
x = df.drop(columns=["Default"])
y = df["Default"]

In [22]:
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_idx, test_idx in split.split(x,y):
    x_train = x.iloc[train_idx]
    x_test = x.iloc[test_idx]

    y_train = y.iloc[train_idx]
    y_test = y.iloc[test_idx]

In [23]:
x_train.isna().sum()

Age                         0
Income                      0
LoanAmount                  0
CreditScore                 0
MonthsEmployed              0
NumCreditLines              0
InterestRate                0
LoanTerm                    0
DTIRatio                    0
Education                   0
EmploymentType              0
MaritalStatus               0
HasMortgage                 0
HasDependents               0
LoanPurpose                 0
HasCoSigner                 0
Loan_to_Income              0
Estimated_EMI               0
EMI_to_Income               0
High_DTI_Flag               0
Low_Credit_Flag             0
Low_Employment_Stability    0
CreditLines_per_Age         0
Thin_Credit_File            0
Stable_Employment           0
Risk_Buffer                 0
Education_Level             0
dtype: int64

In [24]:
num_attribs = [
    "Age",
    "Income",
    "LoanAmount",
    "CreditScore",
    "MonthsEmployed",
    "NumCreditLines",
    "InterestRate",
    "LoanTerm",
    "DTIRatio",

    # Engineered features
    "Loan_to_Income",
    "Estimated_EMI",
    "EMI_to_Income",
    "High_DTI_Flag",
    "Low_Credit_Flag",
    "Low_Employment_Stability",
    "CreditLines_per_Age",
    "Thin_Credit_File",
    "Stable_Employment",
    "Risk_Buffer",
    "Education_Level"
]


cat_attribs = [
    "Education",
    "EmploymentType",
    "MaritalStatus",
    "HasMortgage",
    "HasDependents",
    "LoanPurpose",
    "HasCoSigner"
]

In [25]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline

num_pipeline = Pipeline(steps=[
    ("scaler", StandardScaler())
])

cat_pipeline = Pipeline(steps=[
    ("onehot", OneHotEncoder(handle_unknown="ignore", drop="first"))
])

In [26]:
from sklearn.compose import ColumnTransformer

preprocessor = ColumnTransformer([
    ("num", num_pipeline, num_attribs),
    ("cat", cat_pipeline, cat_attribs)
])

In [39]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    roc_auc_score,
    classification_report,
    confusion_matrix
)

# Build pipeline
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', LogisticRegression(
        class_weight='balanced',
        max_iter=1000,
        random_state=42
    ))
])

# Train
model.fit(x_train, y_train)

# Predict probabilities
y_proba = model.predict_proba(x_test)[:, 1]

# Apply custom threshold
threshold = 0.40
y_pred = (y_proba >= threshold).astype(int)

# Evaluate
print("ROC-AUC:", roc_auc_score(y_test, y_proba))
print(f"Confusion Matrix (threshold = {threshold}):")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

ROC-AUC: 0.7614626326924245
Confusion Matrix (threshold = 0.4):
[[24032 21107]
 [ 1067  4864]]
              precision    recall  f1-score   support

           0       0.96      0.53      0.68     45139
           1       0.19      0.82      0.30      5931

    accuracy                           0.57     51070
   macro avg       0.57      0.68      0.49     51070
weighted avg       0.87      0.57      0.64     51070



In [32]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    roc_auc_score,
    classification_report,
    confusion_matrix
)

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', DecisionTreeClassifier(
        class_weight='balanced',
        max_depth=6,
        min_samples_leaf=50,
        random_state=42
    ))
])

model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_proba = model.predict_proba(x_test)[:, 1]
print("ROC-AUC:", roc_auc_score(y_test, y_proba))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

ROC-AUC: 0.7360673409375411
[[30503 14636]
 [ 1944  3987]]
              precision    recall  f1-score   support

           0       0.94      0.68      0.79     45139
           1       0.21      0.67      0.32      5931

    accuracy                           0.68     51070
   macro avg       0.58      0.67      0.56     51070
weighted avg       0.86      0.68      0.73     51070



In [33]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    roc_auc_score,
    classification_report,
    confusion_matrix
)

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(
        class_weight='balanced',
        n_estimators=200,
        max_depth=12,
        min_samples_leaf=50,
        random_state=42,
        n_jobs=-1
    ))
])

model.fit(x_train, y_train)
y_pred = model.predict(x_test)
y_proba = model.predict_proba(x_test)[:, 1]
print("ROC-AUC:", roc_auc_score(y_test, y_proba))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

ROC-AUC: 0.753721258961841
[[33881 11258]
 [ 2252  3679]]
              precision    recall  f1-score   support

           0       0.94      0.75      0.83     45139
           1       0.25      0.62      0.35      5931

    accuracy                           0.74     51070
   macro avg       0.59      0.69      0.59     51070
weighted avg       0.86      0.74      0.78     51070



In [37]:
from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score, classification_report, confusion_matrix


model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', XGBClassifier(
    n_estimators=400,
    max_depth=4,
    learning_rate=0.05,
    scale_pos_weight=7.6,  # approx 88/12
    eval_metric='auc'
)
    )
])

model.fit(x_train, y_train)

y_pred = model.predict(x_test)
y_proba = model.predict_proba(x_test)[:, 1]

print("ROC-AUC:", roc_auc_score(y_test, y_proba))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

thresholds = [0.5, 0.4, 0.3, 0.25, 0.2]

for t in thresholds:
    print(f"\n===== Threshold = {t} =====")
    
    y_pred_thresh = (y_proba >= t).astype(int)
    
    print(confusion_matrix(y_test, y_pred_thresh))
    print(classification_report(y_test, y_pred_thresh))

ROC-AUC: 0.7586921107389715
[[31646 13493]
 [ 1881  4050]]
              precision    recall  f1-score   support

           0       0.94      0.70      0.80     45139
           1       0.23      0.68      0.35      5931

    accuracy                           0.70     51070
   macro avg       0.59      0.69      0.57     51070
weighted avg       0.86      0.70      0.75     51070


===== Threshold = 0.5 =====
[[31646 13493]
 [ 1881  4050]]
              precision    recall  f1-score   support

           0       0.94      0.70      0.80     45139
           1       0.23      0.68      0.35      5931

    accuracy                           0.70     51070
   macro avg       0.59      0.69      0.57     51070
weighted avg       0.86      0.70      0.75     51070


===== Threshold = 0.4 =====
[[24834 20305]
 [ 1137  4794]]
              precision    recall  f1-score   support

           0       0.96      0.55      0.70     45139
           1       0.19      0.81      0.31      5931

   